//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePersonalDetail
    {
        public int PersonalDetailID { get; set; }
        public int EmployeeId { get; set; }
        public int BranchId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<short> Gender { get; set; }
        public string BirthCountry { get; set; }
        public string CitizenshipCountry { get; set; }
        public string FatherName { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public string SpouseName { get; set; }
        public Nullable<System.DateTime> MarriageDate { get; set; }
        public Nullable<short> ResidentialStatus { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string EmergencyContactNumber { get; set; }
        public string EmergencyContactName { get; set; }
    }
}
