//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpSalaryStructureDetail
    {
        public int EmployeeId { get; set; }
        public int BranchId { get; set; }
        public string ContributionRegister { get; set; }
        public string Computation { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Code { get; set; }
    }
}
