//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public int LeaveId { get; set; }
        public string CountryName { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> PaidLeavesPerYear { get; set; }
        public Nullable<decimal> PaidLeavesPerMonth { get; set; }
        public Nullable<bool> IsPaidLeaveCarryForward { get; set; }
        public string CarryForwardPerYear { get; set; }
        public Nullable<int> SickLeavesPerYear { get; set; }
        public Nullable<decimal> SickLeavesPerMonth { get; set; }
        public Nullable<bool> IsSickLeaveCarryForward { get; set; }
        public Nullable<decimal> CarryForwardSickLeaves { get; set; }
        public Nullable<int> CasualLeavesPerYear { get; set; }
        public Nullable<decimal> CasualLeavesPerMonth { get; set; }
        public Nullable<bool> IsCasualLeaveCarryForward { get; set; }
        public Nullable<long> BranchId { get; set; }
    }
}
