//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherLeave
    {
        public int LeaveId { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
        public Nullable<decimal> LeavesPerYear { get; set; }
        public Nullable<decimal> LeavesPerMonth { get; set; }
        public bool IsCarryForward { get; set; }
        public Nullable<decimal> CarryForward { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public Nullable<short> LeaveYear { get; set; }
    }
}
