//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayslipBatchHeader
    {
        public int BatchHeaderId { get; set; }
        public string BatchNo { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<byte> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<decimal> TotalSalary { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
