//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryRuleDetail
    {
        public int RuleDetailId { get; set; }
        public string ConditionBased { get; set; }
        public string AmountType { get; set; }
        public string PythonCode { get; set; }
        public string ContributionRegister { get; set; }
        public int RuleId { get; set; }
    }
}
