//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryStructureDetail
    {
        public int StructureDetailID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string RegisterCode { get; set; }
        public string ComputationCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsActive { get; set; }
        public int StructureID { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string PaymentType { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
