//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryStructureHeader
    {
        public int StructureID { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> TotalGross { get; set; }
        public Nullable<decimal> TotalDeductions { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> EmpContribution { get; set; }
    }
}
